### ISSUE TITLE
[Task] Finalização Histórico 

### ISSUE THREAD

**Issue by lucasfs1007** [fga-eps-mds/GFour-Invext#100]
### O que precisa ser feito?
Ajustes na tela de históricos do usuário e conexão com o Back
### Por que precisa ser feito?
Para que o usuário possa visualizar em tabelas os dados relacionados com suas ações cadastradas
### Critério de Aceitação
Ser possível visualizar os dados armazenados no banco de dados nas tabelas.

**Comment by amanda-noda** [comment]
A branch que será utilizada para a finalização do histórico será 100-Front_Finaliza_Historico.

**Comment by amanda-noda** [comment]
A tela de Histórico foi refatorada e trocada a table basic por uma tabela um pouco mais complexa/completa com o datagrid, que permite muito mais interação com os dados do hitórico, falta a integração com o back.

**Comment by luciano-freitas-melo** [comment]
FInalizada a integração de requisição do histórico

**Comment by luciano-freitas-melo** [comment]
Integração da parte de excluir ativo realizada

**Comment by luciano-freitas-melo** [comment]
Dúvidas sobre como será feita a parte de editar ativo @lucasfs1007 

Podemos usar a mesma tela de cadastro de ativos, que teria que ter algumas alterações para ficar viável
OU
Criamos outra tela, por exemplo, uma modal simples, para o usuário editar as informações na mesma tela de histórico e não precisar ir para outra tela separada. Mas daí seria um componente novo (mas dá pra pegar os componentes da tela de cadastro de ativos)
