### ISSUE TITLE
[US 16] Criação Página da Carteira

### ISSUE THREAD

**Issue by antonioleaojr** [fga-eps-mds/GFour-Invext#107]
### 📗 Resumo
**Como** [Quem?]
**Eu quero/desejo** 
Criar a tela da carteira
**Para** 
Para que seja possível a visualização do patrimônio e rentabilidade.
 
#### Critério de Aceitação 1
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

#### Critério de Aceitação 2
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado
 
#### Link para Figma
[Link para a página do figma](https://www.figma.com/file/GWE5C8yo9JrKad3GFunhmk/Prot%C3%B3tipo-Invext?node-id=43%3A196)
 
#### Links
Quaisquer links para informações técnicas. como: Documentação, Diagramas de Arquitetura ...

### Notas / Informações Adicionais
Quaisquer anotações relevantes que tenham sido feitas durente as plannings ou conversas do membros sobre a história
 
###  🚩ToDo
- [ ] Criação da tela

**Comment by antonioleaojr** [comment]
- Criei a nova branch para que seja possível começar a implementação amanhã

**Comment by amanda-noda** [comment]
Será usada a branch 107-Front_Carteira para a implementação da tela carteira

**Comment by lucasfs1007** [comment]
A estilização da tela para um momento inicial está finalizada. Precisaremos verificar se a formatação atual atende bem a visualização dos dados da tabela, em caso contrário teremos de tomar novas decisões quanto refatoramento para que possamos abrir mais espaço para visualização.

**Comment by lucasfs1007** [comment]
foi sugerido fazer uma quebra dessa tela em mais duas

**Comment by lucasfs1007** [comment]
A tela foi devidamente finalizada .
