### ISSUE TITLE
[🐞BUG] Venda de ativos

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#111]
### Ambiente
* OS: Ubuntu
* Nome do Browser e versão: Chrome
 
### Pré-condição
* Usuário logado
* Nenhuma compra ou venda realizada no ativo ainda
 
### Passos para reproduzir
1. Ir para a página de Ações
2. Selecionar um ativo que não tenha sido comprado nem vendido pelo usuário
3. Colocar os outros campos (quantidade, preço e data)
4. Clicar no botão de Vendeu

 
### Comportamento Atual
* O ativo não é vendido, mas não é mostrado uma mensagem de erro no front, pois ocorre um "crash" no backend e não retorna nenhuma resposta no response
 
### Comportamento Esperado
* O backend deveria retornar uma response para o front, que apresenta a mensagem de erro para o usuário

### Screenshots
Erro que ocorre quando no backend
![image.png](https://images.zenhubusercontent.com/612e94cf0aa9b5314c653695/489fa4fd-8b5b-416e-a936-f427ba2c7b87)

### Informações Adicionais
* Quando esse bug ocorre não é mais possível utilizar nada no site, pois o backend não volta a funcionar depois do crash sem ter que reiniciar o servidor.

**Comment by luciano-freitas-melo** [comment]
@LeonardoPadre dá uma olhada aqui por favor :D

**Comment by LeonardoPadre** [comment]
[https://github.com/fga-eps-mds/GFour-Invext/commit/4055421e7388546e2de7f4acdb7bb507db3194e4?diff=unified](Comit) com a resolução do bug
