### ISSUE TITLE
[Task] Finalização da tela de rentabilidade

### ISSUE THREAD

**Issue by lucasfs1007** [fga-eps-mds/GFour-Invext#122]
### O que precisa ser feito?
Finalização da tela de rentabilidade com os dados da tabela e os gráficos
### Por que precisa ser feito?
Para dar uma segunda visualização dos dados dos ativos
### Critério de Aceitação
Visualização dos gráficos com os dados dos ativos e visualização das tabelas.
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

**Comment by amanda-noda** [comment]
Tabela já atualizada, só falta integração, iniciarei o desenvolvimento do gráfico escolhido

**Comment by amanda-noda** [comment]
a Branch que será usada para finaalizar a tela de rentabilidade é a 122-Front_Finaliza_Rentabilidade

**Comment by amanda-noda** [comment]
Ao iniciar a implementação do gráfico, gerou u. Bug na tela de centralização de componentes a serem resolvidos

**Comment by lucasfs1007** [comment]
Atualmente seguimos com alguns problemas nos dados, pois o Back ainda está fazendo tratamento dos erros para que possamos mostrar com uma maior eficiência no Front.

**Comment by lucasfs1007** [comment]
Esse é prevista como a última issue de programação para o Front-end na R2. O grupo combinou de finalizar outras demais partes após a entrega.
