### ISSUE TITLE
[Task] Criar a parte de rentabilidade

### ISSUE THREAD

**Issue by LeonardoPadre** [fga-eps-mds/GFour-Invext#126]
### O que precisa ser feito?
- Os calculos relacionados a rentabilidade da carteira
### Por que precisa ser feito?
- Para que o front possa gerar o grafico
### Critério de Aceitação

**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

**Comment by lucasfs1007** [comment]
@LeonardoPadre Quando estiver pronta essa parte faz o PR para termos esses dados no Front por favor.

**Comment by lucasgcaldas** [comment]
@LeonardoPadre Da uma revisada nos calculos que eu modifiquei ai
