### ISSUE TITLE
[FRONT] Prototipação no Figma

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#14]
🖥️Desenvolver o protótipo do projeto 🖥️
A prototipação será desenvolvida baseada no protótipo de baixa fidelidade:
[Imagem Primeiro Protótipo](https://github.com/fga-eps-mds/GFour-Invext/blob/main/PrimeiroPrototipo.jpg)

Ficar atento as funcionalidades que foram desenvolvidadas no Lean Inception
[Board Lean Inception - Miro](https://miro.com/app/board/uXjVOqiqKNo=/)

◍ Tasks:
#### Alterações
- [x] Adicionar campo nome e data de nascimento(obrigatório) em cadastro de usuário e telefone (opcional)
- [x] Remover parte do endereço do Meu Perfil e alterar nome para nome completo e remover sobrenome
- [x] Botão alterar senha
- [x] Botão Desativar Conta e Convidar Amigo para Meu Perfil e remover Configurações
- [x] Carteira: Aumento de informações da tabela (cotação, preço médio, diferença%, quantidade)
![Exemplo de tabela dos ativos](https://images.zenhubusercontent.com/612e94cf0aa9b5314c653695/9d053dab-67b0-497e-9dff-51cde958331e)
- [x] Carteira: Mudar o nome de Patrimônio -> Resumo / Rentabilidade-> Patrimônio
- [x] Cadastro de Ativos: Remover Instituição Financeira e Colocar Ativo em Destaque

#### Novos Itens
- [x] gráfico de evolução de patrimônio em Patrimônio
 ![Exemplo de gráfico de evolução de patrimônio](https://images.zenhubusercontent.com/612e94cf0aa9b5314c653695/34f37b0b-f24c-4309-8951-99ada9c5ada9)
- [x] Tela de editar e excluir ativos
- [x] Botão de logoff na sidebar (embaixo de configurações)

### Informações Adicionais
Meu Perfil: Nome completo e data de nascimento não podem ser alterados pelo usuário
[Link do Figma](https://www.figma.com/file/GWE5C8yo9JrKad3GFunhmk/Prot%C3%B3tipo-Invext?node-id=0%3A1)

**Comment by amanda-noda** [comment]
- Adicionar Tela para cadastro de Ações 
- Adicionar Tela de acompanhamento de rendimento 
- Adicionar Tela de Filtro com filtragem de ativos
- Na parte superior do menu "minha carteira", concentrar toda as informações diretas sobre ações em uma lista com scroll. Informações sobre as ações em colunas: Nome, Sigla, Porcentagem, Preço médio, Valor atual, Quantidade, Rendimento histórico (desdo primeiro dia que comprou o ativo).
- Na parte inferior aba "patrimonio", algo parecido com o "kinvo_4.jpg"(grafico).
- Na parte inferior aba "rentabilidade", algo parecido com o "trademap_2.jpg".

**Comment by luciano-freitas-melo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/G4---MDS-62ae0e2458c26d001a36c995/issues/fga-eps-mds/GFour-Invext/14?planning-poker) with ZenHub @amanda-noda @lucasgcaldas @zjosuez @LeonardoPadre

**Comment by lucasfs1007** [comment]
- @amanda-noda @antonioleaojr  depois deem uma olhada na versão que subimos ontem já do código, adicionamos uma setinha para retornar a página anterior e o hover na mesma e no botão de cadastro que há uma troca de cor ao passar o mouse em cima dele.
