### ISSUE TITLE
Diagrama de Casos de Uso

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#20]
### O que precisa ser feito?
implementar o diagrama de Casos de Uso do projeto

### Critério de Aceitação

**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

**Comment by LeonardoPadre** [comment]
Primeira versão do diagrama de casos de uso finalizada (sujeito a alterações futuras caso haja alguma revisão)
