### ISSUE TITLE
Revisão do documento de arquitetura

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#22]
### O que precisa ser feito?
Revisão do conteúdo que já está no documento de arquitetura e inserir os diagramas já produzidos

### Por que precisa ser feito?
Para termos uma versão final do documento e termos mais visões acerca das informações contidas nele

### Critério de Aceitação

**Dada(o)** o doc de arquitetura já realizado
**Quando** revisar o conteúdo e inserir os diagramas de classe e pacotes
**Então** um documento mais completo e já disponível no gitpages

**Comment by lucasfs1007** [comment]
Dei uma complementada em algumas coisas...esperar apenas o @zjosuez  dar uma olhada para fecharmos de vez o docs

**Comment by lucasfs1007** [comment]
c
