### ISSUE TITLE
Revisão Diagrama de Classes e Pacotes

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#27]
🖥️Revisão 🖥️
Mesclar informações obtidas do lean inception e do protótipo
◍ Tasks:
- [x] Diagrama de Classes de acordo com o Lean Inception
- [x] Classes da camada de View e Controller (Padrão MVC)
- [ ]

**Comment by lucasfs1007** [comment]
- reposicionei melhor o diagrama de classes, acredito que não há muitas classes a mais. Devemos acrescentar o relacionamento entre elas.
- https://lucid.app/lucidchart/7f679eaa-73b0-4c54-8cd8-e91cf22239d2/edit?viewport_loc=-523%2C-30%2C2827%2C1411%2C0_0&invitationId=inv_b7296629-3eb3-4a54-a40f-c2841c7d6323#

**Comment by lucasfs1007** [comment]
Eu coloquei o preço médio e o preço atual dentro de ações...pq elas pertencem a cada tipo de ação e não a cada patrimonio. E o patrimonônio corresponde exatamente a um conjunto de ações.

**Comment by zjosuez** [comment]
@lucasfs1007 @lucasgcaldas  Alterei algumas coisas do diagrama de classes e implementei a arquitetura MVC, deem uma olhada lá

**Comment by lucasfs1007** [comment]
@lucasgcaldas @zjosuez  revisei aqui e estou de acordo com todas as mudanças. Acredito que fechamos a task já. @lucasgcaldas quando revisar fecha a task por favor se tiver tudo de acordo para você também

**Comment by lucasgcaldas** [comment]
maravilha, pessoal @lucasfs1007 @zjosuez
