### ISSUE TITLE
Badge Better Code Hub

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#46]
### Tasks
- [x] Aprender como funciona o Bagde para passar para o restante do time
- [x] Aplicar dentro do projeto

[Site Better Code Hub]((https://bettercodehub.com/))

**Comment by lucasfs1007** [comment]
Os Badges basicamente são informações acerca do projeto que devem ficar em nosso readme. Essas informações por exemplo devem conter as tecnologias, os contatos da equipe do projeto e e o status do projeto, o que já temos.
