### ISSUE TITLE
[🐞BUG] Login de Usuário

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#48]
### Ambiente
* OS: Ubuntu lts
* Versão do Node : 16.16.0
* Versão do Npm : 8
* Nome do Browser e versão: Chrome
 
### Pré-condição
* Usuário cadastrado no banco
 
### Passos para reproduzir
1. Insira o email correto do usuário
2. Digite a senha errada do usuário
3. É mostrada uma mensagem de erro: "senha incorreta"
4. Coloque a senha certa
 
### Comportamento Atual
* É apresentado uma mensagem de erro: "Erro, tente novamente"
 
### Comportamento Esperado
* Apresentar a mensagem de usuário logado com sucesso

### Screenshots
![image.png](https://images.zenhubusercontent.com/612e94cf0aa9b5314c653695/e29a2dfe-b403-463b-871a-8f5e4df7a34c)

**Comment by lucasfs1007** [comment]
- Relembrar de ajustarmos as fontes para melhor harmonizar o projeto (front).

**Comment by luciano-freitas-melo** [comment]
Corrigido bug no commit a5831d8792f71d6d4c9dea84e3edeebfb3f8796c, o problema estava em alguns if-elses no frontend.
