### ISSUE TITLE
Front-end

### ISSUE THREAD

**Issue by MariaAbritta** [fga-eps-mds/GFour-Invext#5]
🖥️ Primeiros passos 🖥️
Entender melhor as configurações do ambiente.

◍ Ambiente:
Configurar o ambiente pessoal para o início do desenvolvimento.
-> Front-end: Windows
   - [x] Amanda
   - [x] Luciano
   - [x] Lucas Felipe
   - [x] Antônio

**Comment by lucasfs1007** [comment]
Pessoal segue um link de um site com um bom material acerca da configuração pro ambiente que estaremos utilizando: https://www.visualdicas.com.br/programacao/react/78-como-instalar-e-utilizar-o-react-no-windows
