### ISSUE TITLE
[Task] Estilização do Projeto

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#55]
### Critério de Aceitação

**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

**Comment by amanda-noda** [comment]
- [ ] Padronizar fonte usual,harmonização
- [ ] Padronizar cores do aplicativo
- [ ] Padronizar ícones usados

**Comment by lucasfs1007** [comment]
- É interessante aquele estudo de cores para melhor encaixar, e uma melhor harmonização da fonte com o design e toda nossa interface, vim comentando com a @amanda-noda nesses últimos dias sobre isso
