### ISSUE TITLE
[Task] Mudanças na prototipação

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#56]
#### Excluir itens que não vão estar na versão final

- [x] Notícias da sidebar

#### Alterações
- [x] Tela de Ações deve ser no formato abaixo:
![photo1659653044.jpeg](https://images.zenhubusercontent.com/612e94cf0aa9b5314c653695/a081bf71-a60a-4e77-8cea-f4fa024d95ec)

### Critério de Aceitação

**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

**Comment by luciano-freitas-melo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/G4---MDS-62ae0e2458c26d001a36c995/issues/fga-eps-mds/GFour-Invext/56?planning-poker) with ZenHub @amanda-noda @antonioleaojr

**Comment by amanda-noda** [comment]
-Trocar a organização dos ícones, tirando o texto deixando mais intuitivo.
-Verificar se somente a tela de histório com as opções de editar e excluir ações se está ok 
-Modificar tela de excluir e editar ações
-Padronizar estilização de telas

**Comment by lucasfs1007** [comment]
Não se esqueçam de editar aquelas alterações relacionadas a parte da sidebar

**Comment by luciano-freitas-melo** [comment]
Feedbacks do protótipo:
- Organização da sidebar (mais especificado no figma)

**Comment by luciano-freitas-melo** [comment]
Feedbacks do protótipo:
- Organização da sidebar (mais especificado no figma)

**Comment by antonioleaojr** [comment]
Dúvida:
- Qual seria a fonte padrão?

**Comment by antonioleaojr** [comment]
Segui a sugestão que o @luciano-freitas-melo deixou comentada no figma sobre a side bar e modifiquei de acordo com o que foi sugerido.

Sugestão de organização da sidebar:
- Colocaria o resumo da carteira como primeiro item, pois será a tela inicial que o usuário irá ver quando abrir o site
- O ícone de meu perfil poderia ir para baixo e ficar junto do de sair

**Comment by lucasfs1007** [comment]
@antonioleaojr  quanto sua dúvida achei um site bem legal até: https://www.hostinger.com.br/tutoriais/melhores-fontes-html
Em outros projetos gosto de trabalhar com sans-serif, acho que ela dá um aspecto não muito enjoativo, fica bem moderno e já vem sendo utilizada em vários projetos por ai

**Comment by amanda-noda** [comment]
Usando um conteúdo muito legal pra deixar o prototipo ainda mais bonito visualmente e também mais organizado, conteúdo: https://youtu.be/5R9jFHlG6ik
