### ISSUE TITLE
[US 07] Criação Página de Compra e Venda de Ativos

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#57]
### 📗 Resumo
**Como** [Quem?]
**Eu quero/desejo** [O que?]
**Para** [Por quê?]
 
#### Critério de Aceitação 1
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

#### Critério de Aceitação 2
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado
 
#### Link para Figma
[Link para a página do figma](http://linkhere.com)
 
#### Links
Quaisquer links para informações técnicas. como: Documentação, Diagramas de Arquitetura ...

### Notas / Informações Adicionais
Quaisquer anotações relevantes que tenham sido feitas durente as plannings ou conversas do membros sobre a história
 
###  🚩ToDo
- [ ] todo1
- [ ] todo2

**Comment by lucasfs1007** [comment]
- Já criei a nova branch e até então fiz a implementação do css base

**Comment by lucasfs1007** [comment]
-Criei um esqueleto base para podermos elaborar a tela mas ainda não consegui testar oq foi implementado por conta das condições da internet. @luciano-freitas-melo precisarei de ajuda para implementar algumas funcionalidades e mascaras que ainda não foram feitas...o css só poderá ser totalmente finalizado quando tivermos a prototipação da sidebar pronta

**Comment by lucasfs1007** [comment]
- Acabei atrasando um pouco mais a issue enquanto esperava uma finalização do prototipo e por conta de alguns imprevistos que ocorreram, @luciano-freitas-melo @antonioleaojr  conto com a finalização do card de vocês para me dar uma mão também

**Comment by amanda-noda** [comment]
Iniciei a produção da sidebar incluindo estilização do projeto

**Comment by lucasfs1007** [comment]
Comecei a ajustar alguns detalhes para poder melhor implementar a parte do desgin e comecei implementar algumas máscasras para validar os campos que temos. Nessa quarta pretendo continuar essa implementação mais lógica

**Comment by lucasfs1007** [comment]
O Design da tela está encaminhado, precisarei da ajuda do @luciano-freitas-melo para implementar algumas validações para o funcionamento da tela
