### ISSUE TITLE
[US 06] Rotas de Usuário Logado/Não Logado

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#58]
### 📗 Resumo
**Como** [Quem?]
**Eu quero/desejo** [O que?]
**Para** [Por quê?]
 
#### Critério de Aceitação 1
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

#### Critério de Aceitação 2
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado
 
#### Link para Figma
[Link para a página do figma](http://linkhere.com)
 
#### Links
Quaisquer links para informações técnicas. como: Documentação, Diagramas de Arquitetura ...

### Notas / Informações Adicionais
Quaisquer anotações relevantes que tenham sido feitas durente as plannings ou conversas do membros sobre a história
 
###  🚩ToDo
- [ ] todo1
- [ ] todo2

**Comment by lucasfs1007** [comment]
- como está a execução dessa issue ? Precisarei de suporte em outra

**Comment by luciano-freitas-melo** [comment]
- Criado branch para lidar com as rotas
- Feito configuração de autenticacao de usuario
- Configuração dos routes
- Configuração na pagina de login
- Adicionado retorno do back pro front do usuario

**Comment by lucasfs1007** [comment]
- Precisamos configurar o Host para visualização a cada tela.
- Precisamos implementar no back um cadastro teste para passar para todo o time de desenvolvimento para que possamos fazer os testes.
