### ISSUE TITLE
[Task] Pesquisa e configuração de Testes no projeto

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#59]
### Critério de Aceitação

**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

**Comment by lucasfs1007** [comment]
https://pt-br.reactjs.org/docs/testing-recipes.html
https://ateliware.com/blog/testes-em-reactjs
https://devporai.com.br/testes-unitarios-em-react/

**Comment by lucasfs1007** [comment]
Em resumo: Temos a possibilidade de usar uma biblioteca chamada "Jest" e o enzyme e vamos rodar como se fosse um novo projeto mas como teste usando essas bibliotecas...aí tem algumas formas de testar componentes e etc. Sugiro que todos deem uma lida um pouco melhor pois é conteúdo bem longo

**Comment by amanda-noda** [comment]
Acho legal também, se em cada sprint, tivesse uma pessoa para testes.

**Comment by antonioleaojr** [comment]
A professora falou hoje sobre o Selenium, acho interessante a gente dar uma olhadinha nesse software.

**Comment by lucasfs1007** [comment]
https://pt-br.reactjs.org/docs/testing.html outra boa referência que encontrei para a parte de testes unitarios

**Comment by lucasfs1007** [comment]
https://www.treinaweb.com.br/blog/o-que-e-selenium O selenium temos que instalar essa IDE deles e por lá podemos simular scripts e comportamentos do usuário...aparentemente é bem simples

**Comment by lucasfs1007** [comment]
https://www.devmedia.com.br/teste-unitario-com-jest/41234
