### ISSUE TITLE
[US 08] Configuração do Banco de Dados para ativos

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#61]
### 📗 Resumo
**Como** [Quem?]
**Eu quero/desejo** [O que?]
**Para** [Por quê?]
 
#### Critério de Aceitação 1
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

#### Critério de Aceitação 2
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado
 
#### Link para Figma
[Link para a página do figma](http://linkhere.com)
 
#### Links
Quaisquer links para informações técnicas. como: Documentação, Diagramas de Arquitetura ...

### Notas / Informações Adicionais
Quaisquer anotações relevantes que tenham sido feitas durente as plannings ou conversas do membros sobre a história
 
###  🚩ToDo
- [ ] todo1
- [ ] todo2

**Comment by lucasgcaldas** [comment]
Me adicionei na issue para dar uma ajudada

**Comment by lucasgcaldas** [comment]
@LeonardoPadre @zjosuez criei a branch pra essa issue em específica e já adicionei a model da "Ação"

**Comment by LeonardoPadre** [comment]
Troquei "Ação" por "Ativo" nos arquivos, visto que não necessariamente serão adicionadas somente ações e modifiquei a model "Ativo".

**Comment by LeonardoPadre** [comment]
- A adição do middleware faz com que seja necessário estar "logado" para que consiga fazer o cadastro do ativo, serve para proteger rotas futuras e abre a possibilidade de puxar dados do usuario "logado".
- A model "Ativos" foi alterada, agora o id guardado se refere ao id do usuario que fez a requisição.
