### ISSUE TITLE
[US 10] Integração back/front Pág de Cadastro de Ativos

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#67]

**Comment by lucasfs1007** [comment]
Eu e o @luciano-freitas-melo estamos executando essa issue utilizando pareamento. Atualmente tal issue segue com atrasos devido a um pull request da parte do Back-End que teve alguns problemas.

**Comment by lucasfs1007** [comment]
Foi aprovado essa noite o pull request com os dados que seriam necessários do back para a execução dessa issue. Com isso, poderemos dar continuidade ao trabalho da mesma.

**Comment by lucasfs1007** [comment]
Foi elaborado alguns ajustes de máscaras no Front-end, ainda falta fazer uma conexão completa da tela com o Back-end
