### ISSUE TITLE
[🐞BUG] Página de Cadastro de Usuário

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#68]
### Passos para reproduzir
1. Acessar a página de cadastro pelo botão de inscreva-se do login
 
### Comportamento Atual
* Página está desconfigurada do modelo anterior
 
### Comportamento Esperado
* Página harmonizada, com os componentes todos dentro da div

### Notas
* O bug ocorreu provalvemente por conta da mudança na estilização do projeto
### Screenshots
![image.png](https://images.zenhubusercontent.com/612e94cf0aa9b5314c653695/4011c7fa-9262-4c6b-86b8-3e092aa89c8a)

**Comment by amanda-noda** [comment]
o bug foi corrigido na branch Front_Sidebar

**Comment by lucasfs1007** [comment]
@amanda-noda ao gerar o pull request da sua branch coloca para fechar essa issue que já fazemos a revisão finalizando ambas.
