### ISSUE TITLE
[Task] Aperfeiçoar o banco de dados dos ativos

### ISSUE THREAD

**Issue by LeonardoPadre** [fga-eps-mds/GFour-Invext#71]
### O que precisa ser feito?
- [x] Criar uma coluna para o id dos ativos cadastrados
- [x] Preenchimento da coluna execução ao cadastrar uma venda/compra
- [x] Verificar se o usuário tem a quantidade que pretende vender
### Por que precisa ser feito?
- Para melhorar a experiência do usuário
### Critério de Aceitação

**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

**Comment by zjosuez** [comment]
Foi criada uma verificação para validar a quantidade de ação e comparar se a quantidade inserida pelo usuário é igual a quantidade cadastrada no banco de dados.

**Comment by LeonardoPadre** [comment]
- Foi retirada a condição relacionada ao cadastro de novos ativos onde limitava a um cadastro por ativo.
