### ISSUE TITLE
[US 11] Timeout de usuario logado Frontend

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#73]
### 📗 Resumo
**Como** [Quem?]
**Eu quero/desejo** [O que?]
**Para** [Por quê?]
 
#### Critério de Aceitação 1
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

#### Critério de Aceitação 2
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado
 
#### Link para Figma
[Link para a página do figma](http://linkhere.com)
 
#### Links
Quaisquer links para informações técnicas. como: Documentação, Diagramas de Arquitetura ...

### Notas / Informações Adicionais
Quaisquer anotações relevantes que tenham sido feitas durente as plannings ou conversas do membros sobre a história
 
###  🚩ToDo
- [ ] todo1
- [ ] todo2

**Comment by lucasfs1007** [comment]
- Por motivo de prioridades de funcionalidades para o escopo atual do projeto, essa issue será executada apenas futuramente.

**Comment by lucasfs1007** [comment]
cancelada
