### ISSUE TITLE
[US 12] Busca de Ativo

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#74]
### 📗 Resumo
**Como** [Quem?]
**Eu quero/desejo** [O que?]
**Para** [Por quê?]
 
#### Critério de Aceitação 1
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

#### Critério de Aceitação 2
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado
 
#### Link para Figma
[Link para a página do figma](http://linkhere.com)
 
#### Links
Quaisquer links para informações técnicas. como: Documentação, Diagramas de Arquitetura ...

### Notas / Informações Adicionais
Quaisquer anotações relevantes que tenham sido feitas durente as plannings ou conversas do membros sobre a história
 
###  🚩ToDo
- [ ] todo1
- [ ] todo2

**Comment by lucasfs1007** [comment]
Acabei de criar a branch e colocar um template base de nossa função

**Comment by lucasfs1007** [comment]
Atualmente estamos com um problema de conexão com o backend, aparentemente a forma em que foi feito essa parte lá inviabiliza de tratarmos a requisição no front.

**Comment by lucasfs1007** [comment]
Vamos finalizar essa issue totalmente  em conjunto com a issue de correção de bug que entrou para essa sprint.
