### ISSUE TITLE
[🐞BUG] - Sidebar 

### ISSUE THREAD

**Issue by amanda-noda** [fga-eps-mds/GFour-Invext#77]
### Passos para reproduzir
1. Acionar a Sidebar em qualquer tela. 
 
### Comportamento Atual
*Quando a tela possui um background a sidebar não consegue ficar sobre a ela.
 
### Comportamento Esperado
*Ao acionar a sidebar em qualquer tela, abrir e ser funcional em qualquer tela e redirecionar para a tela desejada.

### Screenshots

![Captura de tela de 2022-08-16 23-52-15](https://user-images.githubusercontent.com/58089751/185406927-a8ba9c51-ea47-4706-a790-9523f4d68b39.png)

![Captura de tela de 2022-08-16 22-06-13](https://user-images.githubusercontent.com/58089751/185406920-60749a46-15d5-4825-b22d-e82e9dc80b3d.png)
06848-0bd3c72b-04c4-4ef1-9a69-40555feb27fb.png)

**Comment by lucasfs1007** [comment]
Acredito que devemos retirar essa parte superior para evitar de destoar do background e da parte lateral. Com isso, podemos reajustar esse icone dentro da própia parte lateral e talvez se implementar uma animação para quando passarmos o mouse por cima (houver). E melhor finalizar os links/icones da barra lateral
