### ISSUE TITLE
[US 14] Criação Página de Histórico de ações

### ISSUE THREAD

**Issue by antonioleaojr** [fga-eps-mds/GFour-Invext#91]
### 📗 Resumo
**Como** [Quem?]
**Eu quero/desejo** 
Começar a criação da tela de histórico de ações
**Para** 
Ser possível visualizar as compras e vendas de ativos
 
#### Critério de Aceitação 1
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

#### Critério de Aceitação 2
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado
 
#### Link para Figma
[Link para a página do figma](https://www.figma.com/file/GWE5C8yo9JrKad3GFunhmk/Prot%C3%B3tipo-Invext?node-id=43%3A196)
 
#### Links
Quaisquer links para informações técnicas. como: Documentação, Diagramas de Arquitetura ...

### Notas / Informações Adicionais
Quaisquer anotações relevantes que tenham sido feitas durante as plannings ou conversas do membros sobre a história
 
###  🚩ToDo
- [x] Criação da página - Histórico de ações

**Comment by amanda-noda** [comment]
Seria interessante acrescentar a opção de editar e excluir através de ícones interativos
