### ISSUE TITLE
[US 15] Alterações na sidebar

### ISSUE THREAD

**Issue by antonioleaojr** [fga-eps-mds/GFour-Invext#92]
### 📗 Resumo
**Como** 
@amanda-noda e @antonioleaojr 
**Eu quero/desejo** 
Trocar o ícone de perfil e confirmação se deseja mesmo sair
**Para**
Melhorar a estética da tela e a parte da confirmação para casos em que o usuário clica sem querer em sair.
 
#### Critério de Aceitação 1
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado

#### Critério de Aceitação 2
**Dada(o)** pré-condição
**Quando** ação
**Então** resultado
 
#### Link para Figma
[Link para a página do figma](https://www.figma.com/file/GWE5C8yo9JrKad3GFunhmk/Prot%C3%B3tipo-Invext?node-id=43%3A196)
 
#### Links
Quaisquer links para informações técnicas. como: Documentação, Diagramas de Arquitetura ...

### Notas / Informações Adicionais
Quaisquer anotações relevantes que tenham sido feitas durente as plannings ou conversas do membros sobre a história
 
###  🚩ToDo
- [x] Mudar ícone de perfil
- [ ] Span de saída

**Comment by lucasfs1007** [comment]
@luciano-freitas-melo você precisa revisar o pull request para que possamos finalizar essa issue.
